### ISSUE TITLE
Example of java code to handle this kind of association

### ISSUE THREAD

**Issue by jmbruel** [mde4edu/java-opposite-references#1]
I often use this example to teach UML itself and to illustrate the differences between a regular (bi-directional) association and an one-direction-only one.

As a concrete example of the required code to maintain this kind of relationship, I made them generate the code from the online version of [Umple](http://cruise.eecs.uottawa.ca/umple/)
(e.g., http://cruise.eecs.uottawa.ca/umpleonline/umple.php?model=161013946507).

You might want to reference this simple URL to show the 216 lines of Java code generated!!

**Comment by kolovos** [comment]
Thanks - that's very helpful! I've added a link to the Umple example in d789b3fe2e0bb48221ce4e14ccd62946aef6d427
